//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的�?
//
//    手动更改此文件可能会导致应用程序中发生异常行为�?
//    如果重新生成代码，则将覆盖对此文件的手动更改�?
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Address()
        {
            this.Customer_Invoice = new HashSet<Customer_Invoice>();
            this.Staff_info = new HashSet<Staff_info>();
            this.Customer_Info = new HashSet<Customer_Info>();
        }
    
        public int Address_id { get; set; }
        public string Street_name { get; set; }
        public string Street_number { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string Country { get; set; }
        public string Postcode { get; set; }
        public string House_number { get; set; }
    
        public virtual ICollection<Customer_Invoice> Customer_Invoice { get; set; }
        public virtual ICollection<Staff_info> Staff_info { get; set; }
        public virtual ICollection<Customer_Info> Customer_Info { get; set; }
    }
}
