//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Address()
        {
            this.Customer_Invoice = new HashSet<Customer_Invoice>();
            this.Staff_info = new HashSet<Staff_info>();
        }
    
        public int Address_id { get; set; }
        public string Street_name { get; set; }
        public string Street_number { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string Country { get; set; }
        public string Postcode { get; set; }
        public string House_number { get; set; }
    
        public virtual ICollection<Customer_Invoice> Customer_Invoice { get; set; }
        public virtual ICollection<Staff_info> Staff_info { get; set; }
    }
}
