//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Invoice
    {
        public Customer_Invoice()
        {
            this.Invoice_Menu = new HashSet<Invoice_Menu>();
        }
    
        public int Invoice_id { get; set; }
        public Nullable<int> Staff_id { get; set; }
        public Nullable<int> Pay_id { get; set; }
        public Nullable<int> Customer_id { get; set; }
        public Nullable<int> Address_id { get; set; }
        public Nullable<System.DateTime> Create_date { get; set; }
        public Nullable<System.DateTime> Deliver_time { get; set; }
        public Nullable<bool> Need_invoice { get; set; }
        public string Invoice_head { get; set; }
        public string Is_delivery { get; set; }
        public Nullable<int> Status_id { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Customer_Info Customer_Info { get; set; }
        public virtual Pay_Info Pay_Info { get; set; }
        public virtual Staff_info Staff_info { get; set; }
        public virtual Status_info Status_info { get; set; }
        public virtual ICollection<Invoice_Menu> Invoice_Menu { get; set; }
    }
}
