//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Info
    {
        public Customer_Info()
        {
            this.Customer_Invoice = new HashSet<Customer_Invoice>();
        }
    
        public int Customer_id { get; set; }
        public string Name { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Phone3 { get; set; }
        public Nullable<System.DateTime> Birthday_date { get; set; }
        public Nullable<int> Address_id { get; set; }
        public string Email { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Age { get; set; }
    
        public virtual ICollection<Customer_Invoice> Customer_Invoice { get; set; }
        public virtual Address Address { get; set; }
    }
}
