//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image_info
    {
        public Image_info()
        {
            this.Menus = new HashSet<Menu>();
            this.Menus1 = new HashSet<Menu>();
        }
    
        public int Image_id { get; set; }
        public string Path { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Menu> Menus { get; set; }
        public virtual ICollection<Menu> Menus1 { get; set; }
    }
}
