//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice_Menu
    {
        public int Invoice_menu_id { get; set; }
        public Nullable<int> Invoice_id { get; set; }
        public Nullable<int> Menu_id { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Customer_Invoice Customer_Invoice { get; set; }
        public virtual Menu Menu { get; set; }
    }
}
