//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice_Menu
    {
        public int Invoice_menu_id { get; set; }
        public Nullable<int> Invoice_id { get; set; }
        public Nullable<int> Menu_id { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Customer_Invoice Customer_Invoice { get; set; }
        public virtual Menu Menu { get; set; }
    }
}
