//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public Menu()
        {
            this.Invoice_Menu = new HashSet<Invoice_Menu>();
        }
    
        public int Menu_id { get; set; }
        public string Menu_name { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Description { get; set; }
        public string Flavor { get; set; }
        public string Rating { get; set; }
        public string Is_available { get; set; }
        public string Is_new { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Is_Activation { get; set; }
        public Nullable<System.DateTime> Create_date { get; set; }
        public Nullable<System.DateTime> Modified_date { get; set; }
        public Nullable<int> Small_Image_id { get; set; }
        public Nullable<int> Big_Image_id { get; set; }
    
        public virtual Image_info Image_info { get; set; }
        public virtual Image_info Image_info1 { get; set; }
        public virtual ICollection<Invoice_Menu> Invoice_Menu { get; set; }
    }
}
