//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的�?
//
//    手动更改此文件可能会导致应用程序中发生异常行为�?
//    如果重新生成代码，则将覆盖对此文件的手动更改�?
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public Menu()
        {
            this.Invoice_Menu = new HashSet<Invoice_Menu>();
        }
    
        public int Menu_id { get; set; }
        public string Menu_name { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Description { get; set; }
        public string Flavor { get; set; }
        public string Rating { get; set; }
        public Boolean Is_available { get; set; }
        public Boolean Is_new { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Boolean Is_Activation { get; set; }
        public Nullable<System.DateTime> Create_date { get; set; }
        public Nullable<System.DateTime> Modified_date { get; set; }
        public Nullable<int> Small_Image_id { get; set; }
        public Nullable<int> Big_Image_id { get; set; }
        public Nullable<int> menu_type_id { get; set; }
    
        public virtual Image_info Image_info { get; set; }
        public virtual Image_info Image_info1 { get; set; }
        public virtual ICollection<Invoice_Menu> Invoice_Menu { get; set; }
        public virtual Menu_type Menu_type { get; set; }
    }
}
