//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_Info
    {
        public Pay_Info()
        {
            this.Customer_Invoice = new HashSet<Customer_Invoice>();
        }
    
        public int Pay_id { get; set; }
        public string Pay_method { get; set; }
        public Nullable<decimal> Delivery_fee { get; set; }
        public Nullable<decimal> Menu_fee { get; set; }
        public Nullable<decimal> Total_fee { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<System.DateTime> Create_date { get; set; }
        public Nullable<System.DateTime> Pay_date { get; set; }
        public string Pay_complete { get; set; }
    
        public virtual ICollection<Customer_Invoice> Customer_Invoice { get; set; }
    }
}
