//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_Info
    {
        public Pay_Info()
        {
            this.Customer_Invoice = new HashSet<Customer_Invoice>();
        }
    
        public int Pay_id { get; set; }
        public string Pay_method { get; set; }
        public Nullable<decimal> Delivery_fee { get; set; }
        public Nullable<decimal> Menu_fee { get; set; }
        public Nullable<decimal> Total_fee { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<System.DateTime> Create_date { get; set; }
        public Nullable<System.DateTime> Pay_date { get; set; }
        public string Pay_complete { get; set; }
    
        public virtual ICollection<Customer_Invoice> Customer_Invoice { get; set; }
    }
}
