//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RestaurantContext : DbContext
    {
        public RestaurantContext()
            : base("name=RestaurantContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Address> Addresses { get; set; }
        public DbSet<Customer_Info> Customer_Info { get; set; }
        public DbSet<Customer_Invoice> Customer_Invoice { get; set; }
        public DbSet<Image_info> Image_info { get; set; }
        public DbSet<Invoice_Menu> Invoice_Menu { get; set; }
        public DbSet<Menu> Menus { get; set; }
        public DbSet<Pay_Info> Pay_Info { get; set; }
        public DbSet<Staff_info> Staff_info { get; set; }
        public DbSet<Status_info> Status_info { get; set; }
    }
}
