//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status_info
    {
        public Status_info()
        {
            this.Customer_Invoice = new HashSet<Customer_Invoice>();
        }
    
        public int Status_id { get; set; }
        public string Description { get; set; }
        public string Cause_description { get; set; }
    
        public virtual ICollection<Customer_Invoice> Customer_Invoice { get; set; }
    }
}
