//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status_info
    {
        public Status_info()
        {
            this.Customer_Invoice = new HashSet<Customer_Invoice>();
        }
    
        public int Status_id { get; set; }
        public string Description { get; set; }
        public string Cause_description { get; set; }
    
        public virtual ICollection<Customer_Invoice> Customer_Invoice { get; set; }
    }
}
