//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.App_GlobalResources
{
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Restaurants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Restaurants()
        {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Restaurants", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 创建时间 的本地化字符串。
        /// </summary>
        public static string Create_date
        {
            get {
                return ResourceManager.GetString("Create_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 详细描述 的本地化字符串。
        /// </summary>
        public static string Description
        {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 风味 的本地化字符串。
        /// </summary>
        public static string Flavor
        {
            get {
                return ResourceManager.GetString("Flavor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否激活 的本地化字符串。
        /// </summary>
        public static string Is_Activation
        {
            get {
                return ResourceManager.GetString("Is_Activation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否可用 的本地化字符串。
        /// </summary>
        public static string Is_available
        {
            get {
                return ResourceManager.GetString("Is_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否新品 的本地化字符串。
        /// </summary>
        public static string Is_new
        {
            get {
                return ResourceManager.GetString("Is_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 菜单名 的本地化字符串。
        /// </summary>
        public static string menuName
        {
            get {
                return ResourceManager.GetString("menuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 菜单ID 的本地化字符串。
        /// </summary>
        public static string Menu_id
        {
            get {
                return ResourceManager.GetString("Menu_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改时间 的本地化字符串。
        /// </summary>
        public static string Modified_date
        {
            get {
                return ResourceManager.GetString("Modified_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 价格 的本地化字符串。
        /// </summary>
        public static string price
        {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数量 的本地化字符串。
        /// </summary>
        public static string Quantity
        {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 评级 的本地化字符串。
        /// </summary>
        public static string Rating
        {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请上传菜单大图片 的本地化字符串。
        /// </summary>
        public static string UploadMenuBigPicture
        {
            get {
                return ResourceManager.GetString("UploadMenuBigPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请上传菜单小图片 的本地化字符串。
        /// </summary>
        public static string UploadMenuSmallPicture
        {
            get {
                return ResourceManager.GetString("UploadMenuSmallPicture", resourceCulture);
            }
        }
    }
}
